### ISSUE TITLE
Возможность использования вашей разработки в свободно распространяемой подсистеме

### ISSUE THREAD

**Issue by LevkinSergey** [Synoecium/Uniform-query-console-1C#1]
Добрый день!
Для обычных форм есть замечательный набор инструментов "Инструменты разработчика 1С", но его невозможно использовать в линуксе и в тонком и веб клиенте.

Поэтому мы решили собрать подобный пакет, но который будет работать только на платформенных механизмах или с использованием кроссплатформенных компонент.

Использование этого пакета инструментов хотим сделать общедоступным(OpenSource), разработку вести через гитхаб с использованием EDT.

Можем ли мы включить в этот набор обработки(или часть идей и функционала) вашей консоли запросов для управляемых форм?

На текущий момент нашли основные инструменты (консоль запросов, консоль кода, редактор реквизитов, консоль компоновки и др.) для включения в инструментарий. Сейчас занимаемся получением одобрения авторов. Часть включаем свои- редактор предопределенных, редактор констант, Групповая обработка

Ссылка на репозиторий с новыми инструментами https://github.com/cpr1c/tools_ui

**Comment by Synoecium** [comment]
Добрый день.
Отличная идея, рад, если моя консоль войдет в кроссплатформенный набор инструментов. В свою очередь, можете создавать issue, если обнаружатся баги или несовместимости с какой-то платформой. Pull-request наверно не получится (по крайней мере пока), так как консоль выложена как epf файл, без декомпиляции в виде текстовых файлов.
